### ISSUE TITLE
pre compo tooling TODO

### ISSUE THREAD

**Issue by selfsame** [selfsame/LD33#1]
[https://github.com/selfsame/tween](https://github.com/selfsame/tween)
- [ ]  implement additive tweens (store delta value change and add delta changes to whatever current value is)
- [ ] multiple channels for properties, maybe use a {:channel "string"} opt to declare, otherwise use one base channel

[https://github.com/selfsame/hard](https://github.com/selfsame/hard)
- [x] proper `children` `descendants` `ancestors` for transform trees
- [ ] `hard.input` make forms for using the configurable named inputs instead of verbose keycodes
- [x] add [story.core](https://gist.github.com/selfsame/dee7fce665ea9836ac3e) to `hard` for predicate/type dispatching
  - [x] test stability of `hard.dispatch, hard.life`
  - [x] remove type dispatching because speed
  - [x] make `before` `after` `check` versions of rule
- [ ] find that debug experiment where you could eval data and configure how gizmos displayed it
- [x] fix hard.animation/Bone visualizer component
### stretch TODO
- [ ] fix up flocking defcomponent and hard.spatial (add attractors, optimize, multiple 'species' of flocks)
- [ ] find/make A\* pathfinding
- [ ] play with navmeshes and write some helper interop
- [ ] hard.audio, programatically play sounds at locations without having to configure the components first.
- [ ] environmental lighting randomizer, instead of wasting time tweaking lights, have a command that randomizes the ambient gradient/ directional light.  When a suitable config is found, be able to spit out data that can be used at runtime
- [ ] shim GUI events (not a great feature when they are hard to compose/config via code)
### other
- [ ] practice setting up mechanim junk for a few animations
